travel/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('', include(("travel_lister.urls"),namespace="travel_lister")),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        re_path(
            r"^media/(?P<path>.*)$",
            serve,
            {
                "document_root": settings.MEDIA_ROOT,
            },
        ),
    ]

travel_lister/urls.py
from django.urls import path

from . import views
app_name = "travel_lister"
urlpatterns = [
    path("", views.index, name="index"),
    path("/generate", views.generate, name="generate"),
    path("/download_file/<str:filename>", views.download_file, name="download_file"),
]

travel_lister/models.py
from django.db import models

# Create your models here.
class Destination(models.Model):
    name = models.TextField(max_length=500)
    uid = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return self.name

travel_lister/views.py
from django.shortcuts import render
from django.http import Http404,FileResponse
from travel.scraper import scrapper
from travel import settings
import os

# Create your views here.
def index(req):
    return render(req,"travel_lister/index.html")

def generate(req):
    if(req.method == "POST"):
        data = req.POST['destination']
        if(data):
            result = scrapper(data)
            if(result["success"]):
                path_to_file = f"media/{settings.MEDIA_ROOT}/{result['filename']}"
                return render(req,"travel_lister/destinations.html",{"data":data,"filename":path_to_file})
            else:
                return render(req,"travel_lister/destinations.html",{"data":"error while getting destinations"})
        else:
            return Http404("bad request")
    else:
        return Http404("Invalid request")
    

def download_file(request, filename):
    file_path = os.path.join(settings.MEDIA_ROOT, filename)
    with open(file_path,"rb") as f:
        response = FileResponse(f)
        response['Content-Disposition'] = 'attachment; filename={}'.format(filename)
        return response

travel_lister/templates/travel_lister/destinations.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/destinations.css' %}">
    <title>Document</title>
</head>

<body>
    <nav>
        <ul>
            <li><a href="/"><img src="{% static 'images/logo.png' %}" class="logo" alt="logo"></a></li>
            <li>Signup</li>
            <li>Login</li>
        </ul>
    </nav>
    <main>
        <div class="left flex-center">
            <img src="{% static 'images/success.png' %}" alt="traveller">
        </div>
        <div class="right flex-center">
            <h1 class="header-text">Generated Destinations</h1>
            {% if data %}
            <div class="dw">
                <h2 class="header-tag-line">{{ data }}</h2>
                {% if filename %}
                <a href="{{filename}}" target="_blank"><button>Download pdf</button></a>
                {% else %}
            </div>
            <h2>Some error</h2>
            {% endif %}
            {% endif %}
        </div>
    </main>


</body>

</html>

travel_lister/templates/travel_lister/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <title>Travel Lister</title>
</head>

<body>
    <nav>
        <ul>
            <li><img src="{% static 'images/logo.png' %}" class="logo" alt="logo"></li>
            {% comment %} <li>Signup</li>
            <li>Login</li> {% endcomment %}
        </ul>
    </nav>
    <header>
        <div class="left flex-center">
            <img src="{% static 'images/travel.png' %}" alt="traveller">
        </div>
        <div class="right">
            <h1 class="header-text">Search & Explore</h1>
            <p class="header-tag-line">Don't miss out on any location</p>
            <form action="{% url 'travel_lister:generate' %}" method="post">
                {% csrf_token %}
                <label for="destination">Destination</label>
                <input required type="text" name="destination" id="destination" placeholder="Enter the destination">
                <button type="submit">Submit</button>
            </form>
        </div>
    </header>
    

</body>

</html>